### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by abart27** [JulianStambuk/Newtonian-Particle-Simulator#2]
## Specifications
Windows 10 64bit
Ryzen 3 3200G
GTX 1050Ti

## Repro
Doubleclick the unpacked portable executable.
Console will appear as child window and show stack trace
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Newtonian_Particle_Simulator.Helper' threw an exception.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Convert.ToDouble(String value)
   at Newtonian_Particle_Simulator.Helper..cctor()
   --- End of inner exception stack trace ---
   at Newtonian_Particle_Simulator.MainWindow.OnLoad(EventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run(Double updateRate)
   at Newtonian_Particle_Simulator.Program.Main()
```
and promptly exits afterward.

**Comment by BoyBaykiller** [comment]
Yeah I am pretty sure that has to do with a bad assumption I make about the format of strings returned from `GL.GetString`
The way I extract the GL and GLSL Versions of the system into doubles looks like this:

```cs
public static readonly double APIVersion = Convert.ToDouble(GL.GetString(StringName.Version).Substring(0, 3));
public static readonly double GLSLVersion = Convert.ToDouble(GL.GetString(StringName.ShadingLanguageVersion));
```
This has worked fine till now, but I guess on your system `GL.GetString` returns a differently formated string.

I updated the release to simply dont check for core extensions anymore lol. There is no reason to parse the API Version into a double anymore. The GLSL thing had no functionality to begin with anyways. Maybe I'll find a better solution some day.

The program now prints out the raw strings. If it doesnt crash anymore you can tell me how the strings are actually formated.
Also make sure to start the program with your dedicated GPU GTX 1050 Ti.

**Comment by tommai78101** [comment]
@JulianStambuk You may also want to update Line 12 of Helper.cs, please:

https://github.com/JulianStambuk/Newtonian-Particle-Simulator/blob/master/Newtonian-Particle-Simulator/src/Helper.cs#L12

Because I'm getting `"3.30 NVIDIA via Cg compiler"` string back for `GL.GetString(StringName.ShadingLanguageVersion)`. This value can't be directly converted to a Double.

Wouldn't it be easier if you updated your main branch, so that future users like me who only pull your source codes can still take a look at it? That is all, thanks.

**Comment by BoyBaykiller** [comment]
@tommai78101 Ok I pushed the changes to `master`. That should fix it.
However note that this program depends on GL 4.5 and GLSL 4.3, so it looks like your system won't be able to run it.

**Comment by tommai78101** [comment]
@JulianStambuk Thanks. It's a great help for everyone.

Still, damn... Here, I thought having a RTX 2070 card should support GL 4.5 and GLSL 4.3, in theory, ...

**Comment by BoyBaykiller** [comment]
@tommai78101 Wait you have a RTX 2070? That should definitely support GL 4.6.
Anyways, I am closing.

**Comment by tommai78101** [comment]
@JulianStambuk  Yeah, I figured it out now.

It has to do with this line in `MainWindow.cs`:

```csharp
public MainWindow() 
            : base(832, 832, new GraphicsMode(0, 0, 0, 0), "Newtonian-Particle-Simulator") { /*WindowState = WindowState.Fullscreen;*/ }
```

Where I need to pass in a new `NativeWindowSettings`, and override `APIVersion` property to `System.Version(4, 6);` to get it to load OpenGL 4.6 and GLSL 4.6.

Otherwise, it defaults to OpenGL 3.3 and GLSL 3.3.

In your README.md, you might also need to specify the minimum requirements is OpenGL 4.5 and GLSL 4.5.

**Comment by BoyBaykiller** [comment]
@tommai78101 Hey, thanks!

Turns out on my system requesting 4.6 returns a Core Profile which means rendering without an VAO wont work anymore (deprecated in core). I could specifically request a Compatibility Context but I am not sure about that. I feel like what you mentioned deserves a dedicated issue. Would you be so kind of creating one?

**Comment by tommai78101** [comment]
@JulianStambuk Dedicated issue added.

**Comment by abart27** [comment]
Awesome, thank you.
